/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "identifier.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_identifier1(void);
extern void test_identifier2(void);
extern void test_identifier3(void);
extern void test_identifier4(void);
extern void test_identifier5(void);
extern void test_identifier6(void);
extern void test_identifier7(void);
extern void test_identifier8(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestIdentifier.c");
  RUN_TEST(test_identifier1, 18); // testname + line number
  RUN_TEST(test_identifier2, 28);
  RUN_TEST(test_identifier3, 38);
  RUN_TEST(test_identifier4, 48);
  RUN_TEST(test_identifier5, 58);
  RUN_TEST(test_identifier6, 68);
  RUN_TEST(test_identifier7, 78);
  RUN_TEST(test_identifier8, 89);

  return (UnityEnd());
}
